language: node_js

node_js:
  - "12"
  - "10"
  - "8"
  - "6"

script:
  - npm run lint-ci
  - npm run test-ci
  - npm run typescript

notifications:
  email:
    on_success: never
    on_failure: always
